const express = require("express");
const cors = require("cors");
const Database = require("better-sqlite3");
const db = new Database("jobmatch.db", { verbose: console.log });

const {
	LoginService,
	RegisterService,
	JobPostsService,
	ApplyService,
	OffersService,
	ProfileService,
} = require("./services");

const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors());

app.use("/login", LoginService);
app.use("/register", RegisterService);
app.use("/job-posts", JobPostsService);
app.use("/apply", ApplyService);
app.use("/offers", OffersService);
app.use("/profile", ProfileService);

const sqliteScript = () => {
	let sql1; // for sql statements

	//sql query
	sql1 = `
      SELECT ID
      FROM hiring_manager
    `;

	let stmt1 = db.prepare(sql1);
	const hiringManagerIds = stmt1.all();

	let businessName = [
		"Livetube",
		"Riffpedia",
		"Npath",
		"Twinder",
		"Kwimbee",
		"Rhycero",
		"Kazu",
		"Janyx",
		"Livefish",
		"Photobug",
		"Linklinks",
		"Yodoo",
		"Linklinks",
		"Zoovu",
		"Voolith",
		"Bubbletube",
		"Vipe",
		"Npath",
		"Digitube",
		"Trilith",
		"Twinder",
		"Digitube",
		"Npath",
		"Aibox",
		"Browsetype",
		"Centimia",
		"Thoughtstorm",
		"Rooxo",
		"Tagcat",
		"Thoughtstorm",
		"Gabvine",
		"Youspan",
		"Jayo",
		"Buzzbean",
		"Skiptube",
		"Wikizz",
		"Muxo",
		"Fivechat",
		"Kare",
		"Zazio",
		"Pixonyx",
		"Podcat",
		"Kazio",
		"Jazzy",
		"Browsedrive",
		"Vimbo",
		"Feedbug",
		"Trudeo",
		"Brightbean",
		"Lajo",
		"Trunyx",
		"Devcast",
		"Babbleblab",
		"Kazu",
		"Eabox",
		"Topdrive",
		"Pixonyx",
		"Tazz",
		"Mudo",
		"Yadel",
		"Gabvine",
		"Podcat",
		"Linkbridge",
		"Avavee",
		"Chatterbridge",
		"Feedfish",
		"Brainverse",
		"Bubblemix",
		"Topiczoom",
		"Trupe",
		"Yadel",
		"Skipfire",
		"Oyoba",
		"Lazz",
		"Eimbee",
		"Quatz",
		"Skinte",
		"Meetz",
		"Oyondu",
		"Muxo",
		"Twimbo",
		"Snaptags",
		"Eire",
		"Feedfish",
		"Zoomdog",
		"Vitz",
		"Kaymbo",
		"Vitz",
		"Photolist",
		"Gabtype",
		"Flashspan",
		"Voonix",
		"Ainyx",
		"JumpXS",
		"Yakidoo",
		"Meembee",
		"Mydo",
		"Trilia",
		"Thoughtsphere",
		"Vidoo",
	];

	let businessIndustry = [
		"Savings Institutions",
		"Commercial Banks",
		"Major Banks",
		"Savings Institutions",
		"Specialty Chemicals",
		"Industrial Machinery/Components",
		"Industrial Machinery/Components",
		"n/a",
		"Computer Software: Prepackaged Software",
		"n/a",
		"Business Services",
		"EDP Services",
		"Major Pharmaceuticals",
		"n/a",
		"Major Banks",
		"Commercial Banks",
		"Railroads",
		"Specialty Insurers",
		"Industrial Machinery/Components",
		"Paper",
		"Electrical Products",
		"Consumer Electronics/Appliances",
		"Telecommunications Equipment",
		"Semiconductors",
		"Forest Products",
		"Investment Managers",
		"n/a",
		"Major Pharmaceuticals",
		"Computer Software: Prepackaged Software",
		"EDP Services",
		"Computer Software: Programming, Data Processing",
		"n/a",
		"Electronic Components",
		"Major Chemicals",
		"Farming/Seeds/Milling",
		"n/a",
		"Biotechnology: Laboratory Analytical Instruments",
		"Business Services",
		"Computer Communications Equipment",
		"Coal Mining",
		"Oil & Gas Production",
		"Consumer Electronics/Appliances",
		"Restaurants",
		"Industrial Specialties",
		"n/a",
		"Telecommunications Equipment",
		"Oil & Gas Production",
		"General Bldg Contractors - Nonresidential Bldgs",
		"Air Freight/Delivery Services",
		"Electric Utilities: Central",
		"n/a",
		"Broadcasting",
		"Hotels/Resorts",
		"Farming/Seeds/Milling",
		"Electrical Products",
		"Medical Specialities",
		"Biotechnology: In Vitro & In Vivo Diagnostic Substances",
		"Medical/Dental Instruments",
		"Electric Utilities: Central",
		"n/a",
		"Major Banks",
		"Major Banks",
		"n/a",
		"Medical/Dental Instruments",
		"Electric Utilities: Central",
		"Real Estate Investment Trusts",
		"Investment Managers",
		"Major Banks",
		"Metal Fabrications",
		"Semiconductors",
		"Investment Managers",
		"Package Goods/Cosmetics",
		"Computer Software: Prepackaged Software",
		"Hotels/Resorts",
		"Commercial Banks",
		"Precious Metals",
		"Automotive Aftermarket",
		"Business Services",
		"Major Pharmaceuticals",
		"Major Banks",
		"n/a",
		"Natural Gas Distribution",
		"Computer Software: Prepackaged Software",
		"Computer Software: Prepackaged Software",
		"Beverages (Production/Distribution)",
		"Major Banks",
		"Major Pharmaceuticals",
		"Property-Casualty Insurers",
		"Major Pharmaceuticals",
		"n/a",
		"Real Estate Investment Trusts",
		"n/a",
		"n/a",
		"Electric Utilities: Central",
		"Biotechnology: Biological Products (No Diagnostic Substances)",
		"n/a",
		"Oil & Gas Production",
		"Homebuilding",
		"Computer Communications Equipment",
		"Business Services",
	];

	let businessDept = [
		"Human Resources",
		"Research and Development",
		"Engineering",
		"Support",
		"Marketing",
		"Accounting",
		"Engineering",
		"Support",
		"Legal",
		"Marketing",
		"Human Resources",
		"Research and Development",
		"Support",
		"Product Management",
		"Training",
		"Services",
		"Business Development",
		"Human Resources",
		"Training",
		"Training",
		"Sales",
		"Human Resources",
		"Engineering",
		"Engineering",
		"Research and Development",
		"Product Management",
		"Training",
		"Services",
		"Marketing",
		"Engineering",
		"Support",
		"Services",
		"Support",
		"Support",
		"Marketing",
		"Marketing",
		"Business Development",
		"Product Management",
		"Human Resources",
		"Product Management",
		"Training",
		"Services",
		"Marketing",
		"Marketing",
		"Training",
		"Accounting",
		"Research and Development",
		"Accounting",
		"Human Resources",
		"Training",
		"Accounting",
		"Services",
		"Support",
		"Research and Development",
		"Marketing",
		"Research and Development",
		"Human Resources",
		"Product Management",
		"Product Management",
		"Marketing",
		"Support",
		"Accounting",
		"Support",
		"Sales",
		"Marketing",
		"Engineering",
		"Training",
		"Accounting",
		"Support",
		"Accounting",
		"Marketing",
		"Product Management",
		"Research and Development",
		"Marketing",
		"Research and Development",
		"Legal",
		"Legal",
		"Legal",
		"Engineering",
		"Product Management",
		"Engineering",
		"Sales",
		"Services",
		"Research and Development",
		"Legal",
		"Human Resources",
		"Product Management",
		"Sales",
		"Legal",
		"Human Resources",
		"Product Management",
		"Business Development",
		"Training",
		"Product Management",
		"Human Resources",
		"Training",
		"Support",
		"Engineering",
		"Accounting",
		"Sales",
	];

	let j = 300;
	try {
		for (let i = 0; i < 2; i++) {
			let sql3;
			sql3 = `UPDATE hiring_manager SET Business_Name = '${businessName[i]}', Business_Industry = '${businessIndustry[i]}', Business_Dept = '${businessDept[i]}' WHERE ID = '${hiringManagerIds[j].ID}'`;
			let stmt3 = db.prepare(sql3);
			stmt3.run();
			j++;
		}
	} catch (error) {
		console.log(error);
	}
	console.log("done");
};

app.listen(3000, () => {
	console.log("Server is running on port 3000");
	sqliteScript();
});
